Repository gardenlinux/package-build, pull requests merged in 2023-11, with the labels that each got.

#6 Feature/3 add folders for organizing script container file etc
  .github/workflows/build_container.yml
  .github/workflows/build_pkg.yml
  README.md
  container/apt/preferences.d/local-pkgs
  container/apt/sources.list.d/debian-src.sources
  container/apt/sources.list.d/local-pkgs.list
  container/bin/build
  container/bin/build_archdep
  container/bin/build_indep
  container/bin/build_source
  container/build.containerfile
  container/conf/pkgs
  container/conf/setup_native
  container/crossbuild.containerfile
  misc/mini_sudo.c
  misc/sudo
  scripts/gh_release
Labels: needs/review, size/s

#16 Feature/13 move build scripts and bind mount
  .github/workflows/build_pkg.yml
  README.md
Labels: needs/review, size/xs

#20 Enhance document and add the miss steps.
  README.md
Labels: needs/review, size/s

#22 Feature/15 enhance default variables management
  container/bin/build_source
Labels: needs/changes, needs/review, size/xs

#21 Feature/2 add support for native package builds
  container/bin/build_source
Labels: needs/review, size/xs

#23 Remove pkg.yml and adjust versioning logic
  .github/workflows/build_pkg.yml
  container/bin/build_source
  container/build.containerfile
  scripts/gh_release
Labels: needs/review, size/s
